version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: emos
      POSTGRES_PASSWORD: 12092003EeEe!?
      POSTGRES_DB: kickalertbox
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
